### ISSUE TITLE
RecurreingJobAttribute timezoneInfo not supported 

### ISSUE THREAD

**Issue by haimYuhter** [icsharp/Hangfire.RecurringJobExtensions#1]
i tried to set timezone for a job using the attribute, but the TimeZoneInfo is not supported as attribute parameter(by c#), my code example:
`[RecurringJob("0 10 * * *", timeZone: TimeZoneInfo.FindSystemTimeZoneById("GMT Standard Time"))]`
i just want to make sure that no matter what is the timezone at the machine this job will run at UTC

**Comment by icsharp** [comment]
Hi ,@haimYuhter 
It is solved to version 1.1.4, and change the default timezone to UTC instead of Local.

**Comment by haimYuhter** [comment]
Thank you very much you are awesome!
