### ISSUE TITLE
向大神提2个建议

### ISSUE THREAD

**Issue by huacxl** [icsharp/Hangfire.RecurringJobExtensions#3]
向大神提2个建议:
1.JOB的配置文件希望可以能支持多个,
类似这样导入:UseRecurringJob(各个配置文件的路径的数组);
2.读入配置文件里程序集的时候,最好可以不仅仅在程序根目录查找,也可以查找配置文件所在目录;
我想象的程序目录如:
hangfireHost/
..jobs/
  ..job1/job1.json,job1.dll
  ..job2/job2.json,job2.dll
    ......

看好不好实现,谢谢!

**Comment by icsharp** [comment]
@huacxl 
最新版本[v1.1.5](https://github.com/icsharp/Hangfire.RecurringJobExtensions/releases/tag/v1.1.5)，测试并反馈下.

**Comment by huacxl** [comment]
@icsharp 
好的,多谢!我明天测试一下

**Comment by huacxl** [comment]
@icsharp 
测试过了,运行正常,谢谢啦!
